### PR TITLE
Verify

### PR DESCRIPTION
**Pull request by PapaChang07**
This is the login verification process, but the Professor will help refining it!

### CODE REVIEW

**Comment by shadhussain12** [comment]
Once this is refined, let's merge it to main. As of now, it isn't quite ready, but getting super close.

**Review by shadhussain12 — COMMENTED** [review]
Looking good, but let's wait before merging. If we can get it a bit more refined, it will be all set.

**Review by ChrisAruiza1015 — COMMENTED** [review]
Looks good to me! Hope the professor can help us finish this

**Comment by jhaluska10** [comment]
I think the code itself looks good and should work well. But from a code cleanliness standpoint maybe we should get rid of some of the console.logs to help with code cleanliness.

**Pull request merged**
