### PR TITLE
List view

### PR DESCRIPTION
**Pull request by ChrisAruiza1015**
Added the sign-in page and updated the CSS

### CODE REVIEW

**Comment by jhaluska10** [comment]
I would say the code looks pretty good to me. But if I could make a suggestion I think it would be best if we were able to make sure our CI checks pass for this branch. So if possible we should try and set it up so we get of this code before merging it.

**Review by PapaChang07 — COMMENTED** [review]
This is fantastic

**Review by shadhussain12 — COMMENTED** [review]
Design looks great, nice work, Topher.

**Comment by ChrisAruiza1015** [comment]
> I would say the code looks pretty good to me. But if I could make a suggestion I think it would be best if we were able to make sure our CI checks pass for this branch. So if possible we should try and set it up so we get of this code before merging it.

Good idea Joseph! I was thinking of having CI checks only on the CImain branch, but it definitely makes more sense to have it on each branch. I'll set that up for my next pull request.

**Pull request merged**
