### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by jhaluska10**
This branch adds testing as well as adds a post method that can be used to update tasks and also a method to fetch individual users, not a whole list.

### CODE REVIEW

**Comment by PapaChang07** [comment]
Looks good!

**Review by PapaChang07 — COMMENTED** [review]
looks good

**Review by ChrisAruiza1015 — COMMENTED** [review]
Looks good to me!

**Comment by jhaluska10** [comment]
Better to merge with list view rather than main

**Pull request closed without merging**
