### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by jhaluska10**
Merges the tests and updated backend to frontend

### CODE REVIEW

**Review by ChrisAruiza1015 — COMMENTED** [review]
Looks good to me! Ready to merge

**Review by PapaChang07 — COMMENTED** [review]
beautiful

**Comment by shadhussain12** [comment]
Looks great, thanks for adding testing to list-view. Should help with rest of deployment.

**Comment by jhaluska10** [comment]
> Looks good to me! Ready to merge

Ok, will make sure to have that done

**Comment by jhaluska10** [comment]
> beautiful

Thank you very much

**Comment by jhaluska10** [comment]
> Looks great, thanks for adding testing to list-view. Should help with rest of deployment.

Yep. I think it will definitely help with the list view. That's why I closed the last pull request that was going to merge into main. I think it would be more useful in the list-view branch.

**Pull request merged**
