### PR TITLE
C imain

### PR DESCRIPTION
**Pull request by PapaChang07**
lol

### CODE REVIEW

**Comment by jhaluska10** [comment]
Looks good to me, but I noticed we have not changed the port on the frontend when we call the FetchAll

**Review by ChrisAruiza1015 — CHANGES_REQUESTED** [review]
Looks like the Heroku is only running on the frontend. I think adding the Heroku API key to the backend yml file would solve this!

**Comment by PapaChang07** [comment]
> Looks like the Heroku is only running on the frontend. I think adding the Heroku API key to the backend yml file would solve this!

Fixed it!

**Comment by PapaChang07** [comment]
> Looks good to me, but I noticed we have not changed the port on the frontend when we call the FetchAll

Fixed it!

**Review by shadhussain12 — APPROVED** [review]
Looks good Norman! Ready to merge with main.

**Pull request merged**
